#!/bin/bash

set -xeuo pipefail

first_arg=${1:-}

if [[ ! "$first_arg" =~ "no-compile" ]]; then
    clojure -Srepro -R:cljs-jvm -m "cljs.main" -v -co "cljsc.edn" -c les.les-script
fi

COMPILED_PATH="out/les-cljs-unbundled.js"
BUNDLED_PATH="les-cljs.js"

yarn -s browserify --node --standalone index $COMPILED_PATH \
  | yarn -s uglifyjs --preamble '#!/usr/bin/env node' -o $BUNDLED_PATH
